name: mystreet_coimbatore
description: A local vendor map app for Coimbatore using OpenStreetMap.
publish_to: 'none' # Remove this if you plan to publish

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^13.0.4             # Use recent stable version
  geolocator_android: ^4.6.1      # Pin to 4.6.1 to avoid Gradle issues
  flutter_map_marker_popup: ^6.0.0
  url_launcher: ^6.2.5
  provider: ^6.1.2
  geocoding: ^2.1.0
  http: ^1.4.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/

# fonts:
#   - family: Poppins
#     fonts:
#       - asset: assets/fonts/Poppins-Regular.ttf
#       - asset: assets/fonts/Poppins-Bold.ttf
#         weight: 700

dependency_overrides:
  geolocator_android: 4.6.1